name: dartlcemodel
description: A Dart library for data loading with reactive cache and loading state.
version: 0.1.0
homepage: https://github.com/motorro/DartLceModel
repository: https://github.com/motorro/DartLceModel.git
issue_tracker: https://github.com/motorro/DartLceModel

environment:
  sdk: '>=2.18.2 <3.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  build_runner: ^2.3.2
  build_test: ^2.1.5
  test: ^1.16.0
  mockito: 5.3.2
  lints: ^2.0.0
  fake_async: ^1.3.1
